### PR TITLE
code to allow showing semi modal view in other orientations besides portrait.

### PR DESCRIPTION
**Pull request by ishaq**
Hi Nathan,

I am trying to make the TDSemiModalView auto-rotate itself e.g. like a UIAlertView would rotate itself to different orientations. So far I have made it to instantiate correctly in all four orientations, thought you might want to take a look and share some ideas on how to achieve auto-rotation.

MI

### CODE REVIEW

**Comment by reednj** [comment]
Thanks for this! I actually don't know much about making the non default orientations work correctly, but it looks promising. Once it is all working I will pull it in.

**Comment by ishaq** [comment]
right, so I can't expect any ideas from you in how to make it rotate. ;-) Let me dig deeper and see if I can find something.

**Comment by reednj** [comment]
I am looking at it now, but I don't have a solution :( It seems to be something to do with the fact that the modal view is added to the main _UIWindow_, instead of the rootView of that window. I think this is not the right thing to do. Ie I should have done this in UIViewController+TDSemiModalExtension.m:

```
[mainWindow.rootViewController.view addSubview:coverView];
[mainWindow.rootViewController.view addSubview:modalView];
```

This fixes the problem of it not rotating when displayed, but it causes the modal view to be positioned incorrectly, I'm seeing if I can fix that now.

**Comment by ishaq** [comment]
if it's rotating fine, positioning should be do-able through some experimentation. I had thought of doing it this way but then I thought it would require a lot of code in the picker controller's `- (void)willAnimateRotationToInterfaceOrientation:(UIInterfaceOrientation)toOrientation duration:(NSTimeInterval)duration;` and therefore kill the purpose of abstracting semi modal view.

I'm a little tied up right now, will take a look at it later tonight (if it's not already fixed by you of course :-) )

**Comment by reednj** [comment]
Oh, you need to add this to the modal view viewDidLoad also:

```
self.view.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
```

I must be either stupid or tired, because I can not make this animation do what I want... :(

**Comment by ishaq** [comment]
as long as the users only have to specify auto-resizing mask on their pickers and don't have to handle rotation themselves, I think we are good to go, no matter if we have to introduce a dirty hack. 

I am sure you are already thought of this but here's my two cents :-)
- get device's orientation changed notifications
- in the `willAnimateRotationToInterfaceOrientation:duration:` modify bounds and transform of a coverflow view to make it look good in the new orientation. if the modal view was contained in coverflow view, it should be get re-scaled automatically. 

like I said, I am working on something totally unrelated right now so don't flame me if what I said above is utterly useless ;-)

**Comment by reednj** [comment]
Nah, there is not need to do that. Changing the orientation with the datepicker up, works _perfectly_, amazingly perfectly after changing to a parent view that gets the rotate notifications (and fiddling with the resize masks etc). Its showing the view in the first place from a non-portrait view that I can't get to work, it always appears in some unexpected place. The co-ordinate system is quite confusing? Like in landscape mode the x&y is swapped around setting the bounds of the view, but _not_ when getting the center of the window.

In any case, I've given up for tonight, I will look at it again tomoz.

**Comment by ishaq** [comment]
if you could share the code, I might be able to see the issue.

**Comment by ishaq** [comment]
because making it appear correctly was working previous (at least for me), no?

**Comment by reednj** [comment]
Yeah, good point, have crack with this code here: https://github.com/reednj/TDSemiModal/tree/ishaq-master

good luck!

**Comment by ishaq** [comment]
I have made it to slide-in/slide-out through correct positions.

There's still a crazy problem left, here's what:
- Launch the demo in portrait of portrait upside-down orientation and click to display semi-modal. it would slide in from bottom of the screen and will show properly.
- However, if right after launching the app, you rotate the device to landscape-left of landscape-right orientation, and **then** click to display semi-modal, it slide in correctly, but date picker won't be displaying where it should. I have probably messed some auto resizing masks but I can't figure out which.

btw, download the code from: http://dl.dropbox.com/u/6845322/reednj-TDSemiModal-bd9e080.zip , I did not know how to check out the code without read-only mode from the url in previous message (may be I should have created another fork?).

I am going to sleep now. let me know if you find the issue.

**Comment by reednj** [comment]
Ok 2 weeks later I've worked this one out, and merged your changes into 'master'

The key was to resize the subviews manually like this. 

```
// http://stackoverflow.com/questions/1088163
for (UIView* subview in datePicker.subviews) {
    subview.frame = datePicker.bounds;
}
```

Thanks stackoverflow!

**Comment by ishaq** [comment]
ah good! I thought you had disappeared.

Thanks to StackOverflow and Apple? What have you done with the docs.

**Pull request merged**
